<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
print(a.ndim)
print(b.ndim)
# ========

2
2


In [3]:
print(a)

[[0.85355114 0.53598406 0.91996195 ... 0.26546668 0.47653535 0.12070389]
 [0.91155972 0.58403048 0.2092101  ... 0.0035933  0.55648703 0.1756408 ]
 [0.18246673 0.79145237 0.63038071 ... 0.53929515 0.42664258 0.38089081]
 ...
 [0.23065618 0.79318147 0.32179212 ... 0.98999839 0.12152183 0.26913057]
 [0.35333982 0.46070956 0.49555124 ... 0.77657436 0.76650231 0.5586115 ]
 [0.92399292 0.12866078 0.63077559 ... 0.04017689 0.11133737 0.70460324]]


In [4]:
print(b)

[[0.03210615 0.57452549 0.73974756 ... 0.52335283 0.12365468 0.51928601]
 [0.71122362 0.18273594 0.45206357 ... 0.29275957 0.00495221 0.27275879]
 [0.72734248 0.11834133 0.44814856 ... 0.87565039 0.02354676 0.22587488]
 ...
 [0.315883   0.28825604 0.8381404  ... 0.45009682 0.86347158 0.12816576]
 [0.99648868 0.42101039 0.53264594 ... 0.36173422 0.71977446 0.36047647]
 [0.77836552 0.62781416 0.04075333 ... 0.70324476 0.96869106 0.08257099]]


In [5]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = np.zeros((a.shape[1],b.shape[0]))
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a)):
                c[i][j] += a[i][k] * b[k][j]
    return c

In [8]:
mult(a,b) == a@b

array([[ True,  True,  True, ...,  True, False, False],
       [ True,  True,  True, ...,  True, False, False],
       [ True, False,  True, ..., False, False, False],
       ...,
       [False,  True,  True, ..., False, False,  True],
       [False, False, False, ..., False, False, False],
       [ True,  True, False, ..., False, False, False]])

In [9]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return a@b

In [10]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 968 ms


In [11]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 0 ns


In [12]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.6836310123835574e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [13]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.51090854 0.92791405 0.98370619] [0.69745818 0.03293822 0.02083237]


In [14]:
def scalar_product(a,b):
    z = 0
    for i in a,:
        for j in b:
            z += i * j
    return z

In [17]:
def np_scalar_product(a,b):
    return a@b

In [18]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 0 ns


0.6448608173688222

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работают с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе программы).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [52]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    return np.sum(np.diag(a)[np.diag(a)%2==0])

In [53]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 8, 5, 3, 9],
       [9, 8, 6, 2, 6],
       [2, 8, 4, 7, 7],
       [5, 8, 3, 9, 7],
       [8, 1, 1, 6, 5]])

In [56]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 0 ns


14

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


​


In [ ]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    #param A: np.array[m,n]
    #YOUR CODE

    result = #YOUR CODE
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    #YOUR CODE

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [ ]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

In [ ]:
np.hsplit