In [1]:
import torch
from torch import nn

In [15]:
from torchsummary import summary

In [2]:
m = nn.Sigmoid()
m

Sigmoid()

In [38]:
summary(m)

Layer (type:depth-idx)                   Param #
└─Sigmoid: 0-1                           --
Total params: 0
Trainable params: 0
Non-trainable params: 0


Layer (type:depth-idx)                   Param #
└─Sigmoid: 0-1                           --
Total params: 0
Trainable params: 0
Non-trainable params: 0

In [39]:
loss = nn.BCELoss(reduction = 'none')
loss

BCELoss()

In [40]:
loss.weight

In [56]:
input = torch.randn(2, requires_grad=True)
input

tensor([1.4304, 0.9148], requires_grad=True)

In [57]:
m(input)

tensor([0.8070, 0.7140], grad_fn=<SigmoidBackward>)

In [58]:
target = torch.empty(2).random_(2)
target

tensor([0., 0.])

In [59]:
output = loss(m(input), target)
output

tensor([1.6449, 1.2517], grad_fn=<BinaryCrossEntropyBackward>)

In [18]:
output.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.